public class PlayingWithDates {
    public void printDateOutput() {
        system.debug(Date.today());

        Date d1 = Date.newInstance(2789, 11, 5);
        system.debug(d1);


        Date d2 = Date.newInstance(1459, 3, 4);
        system.debug(d2);
         integer dayInt = 7;
         integer monthInt = 4;
         integer yearInt = 1979;

         Date newdate = Date.newInstance(yearInt, monthInt, dayInt);
         system.debug(newDate);




        

    }
}
